In [ ]:
import httpx
import os
cookies = {'session': os.environ['AOC_SESSION']}
res = httpx.get('https://adventofcode.com/2025/day/6/input', cookies=cookies)

In [ ]:
instructions = list(res.iter_lines())
numbers = instructions[:-1]
signs = instructions[-1]

In [ ]:
sample_input = '''123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   +'''.splitlines()


In [ ]:
numbers = sample_input[:-1]
signs = sample_input[-1]

### Part 1

In [ ]:
import math

In [ ]:
total = 0
for s,nums in zip(signs.split(), zip(*[list(x) for x in [map(int, number.split()) for number in numbers]])):
    if s == '*': 
        total+=math.prod(nums)
    elif s == '+': 
        total+=sum(nums)
    else: 
        print(s,nums)
print(total)

7644505810277


Ok, now I have a second value I would also like to combine with these so it should be something like '*', (123, 45, 6)
'+', (328, 64, 98)
'*', (51, 387, 215)
'+', (64, 23, 314)

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

You're close! You need to extract the individual signs from your `signs` string and pair them with your tuples.

Take a look at what `signs` currently looks like — it has spaces between the operators. How might you extract just the `*` and `+` characters? (Hint: think about `split()` or filtering for non-space characters.)

Once you have a list of signs, you can `zip` them together with your tuples just like you did with the numbers.

Can I (and should I) use the same zip? or will this be a second zip outside the first zip?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Great question! You'll use a **second `zip`** — an outer one that combines the signs with the tuples you're already creating.

Think of it this way:
- Your current `zip` creates the tuples of numbers (one column at a time)
- The new `zip` will pair each sign with each of those tuples

So the structure would be: `zip(signs_list, <your current zip expression>)`

Does that make sense? Would you like to try writing it out?

This isn't quite what I was expecting.  I was expecting to get these zipped together vertically so I was expecting to get 123, 45, 6 together, 328, 64, 98.  Did I do something wrong with zip?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

You're very close! The issue is that you're passing a single list to `zip()`. When you do `zip([list1, list2, list3])`, it just wraps each list in a tuple.

To zip the inner lists together, you need to *unpack* them using `*` so that `zip` receives them as separate arguments.

Try adding `*` before your list comprehension. Does that give you a hint about what to change?

In [ ]:
list(x)

[6, 98, 215, 314]

In [ ]:
list(map(int, tmp.split()))

[123, 328, 51, 64]

In [ ]:
signs.split()

['*', '+', '*', '+']

In [ ]:
numbers

['123 328  51 64 ', ' 45 64  387 23 ', '  6 98  215 314']

is there a way to multiple a list of numbers together similar to how sum adds the list of numbers together?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Yes! There are a few ways to multiply a list of numbers together:

1. **Using `math.prod()`** (Python 3.8+) - this is the direct equivalent to `sum()`:
   ```python
   import math
   math.prod([2, 3, 4])  # Returns 24
   ```

2. **Using `reduce()` with `operator.mul`**:
   ```python
   from functools import reduce
   from operator import mul
   reduce(mul, [2, 3, 4])  # Returns 24
   ```

3. **Using `numpy.prod()`** (if you're already using numpy):
   ```python
   import numpy as np
   np.prod([2, 3, 4])  # Returns 24
   ```

The first option (`math.prod()`) is probably the simplest and most similar to `sum()`. 

Which approach sounds best for what you're working on?

What is a straightforward way to split this into numbers?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Looking at your string, you can use the `.split()` method without any arguments. This will automatically split on any whitespace (spaces, tabs, etc.) and ignore extra spaces:

```python
tmp.split()
```

This should give you a list of the number strings: `['123', '328', '51', '64']`

Want to try it and see if that works for your needs?

### Part 2

In [ ]:
instructions = list(res.iter_lines())
numbers = instructions[:-1]
signs = instructions[-1]

In [ ]:
numbers = sample_input[:-1]
signs = sample_input[-1]

In [ ]:
from collections import defaultdict
col_nums = defaultdict(str)
for row in numbers:
    for i,space in enumerate(row):
        col_nums[i]+=space
sign_list = signs.split()
sign_list.reverse()
s = sign_list.pop()
eq_result=0 if s=='+' else 1
total_result = 0
for _,num in col_nums.items():
    try:
        if s == '+': 
            eq_result+=int(num)
        elif s == '*':
            eq_result*=int(num)
        else: 
            raise
        # print(num, eq_result) 
    except ValueError: # Split between equations 
        total_result+=eq_result
        s = sign_list.pop()
        eq_result=0 if s=='+' else 1
total_result+=eq_result
print(total_result)

In [ ]:
signs

'*   +   *   +'

In [ ]:
[1,2,3].reverse()

In [ ]:
total_result

13247

In [ ]:
num

'    '