In [ ]:
import httpx
import os
cookies = {'session': os.environ['AOC_SESSION']}
res = httpx.get('https://adventofcode.com/2025/day/3/input', cookies=cookies)

In [ ]:
instructions = list(res.iter_lines())

In [ ]:
sample_input = '''987654321111111
811111111111119
234234234234278
818181911112111'''

### Part 1

In [ ]:
si = sample_input.splitlines()[3]

In [ ]:
sample_input.splitlines()

['987654321111111', '811111111111119', '234234234234278', '818181911112111']

In [ ]:
total_output_joltage=0
for si in instructions: #sample_input.splitlines():
    si_end = si[-1]
    sorted_si = sorted(si, reverse=True) # Check everything except the last digit since that won't be able to be combined with a second option
    sorted_si.remove(si_end)
    starting_digit_position = si[:-1].find(sorted_si[0])
    second_digit_candidates = si[starting_digit_position+1:]+si_end
    sorted_second_candidate = sorted(second_digit_candidates, reverse=True)
    second_digit_position = -1
    for next_highest_num in sorted_second_candidate: 
        # print(f"looking for {next_highest_num}")
        second_digit_position = second_digit_candidates.find(next_highest_num)
        if second_digit_position != -1: 
            # print(f"found {second_digit_candidates[second_digit_position]}")
            break
    # print(si)
    # print(si[starting_digit_position]+second_digit_candidates[second_digit_position])
    total_output_joltage += int(si[starting_digit_position]+second_digit_candidates[second_digit_position])
total_output_joltage

17109

### Part 2

I don't really like my solution to part 1 and part 2 of my advent of code challenge is asking me to put together the largest number that I can with 12 digits (rather than the 2 digits I stumbled my way through above).  I think sorting the values is a good way to start finding the largest possible value, and maybe that is what I need to do for part 2. So I guess the things I need to change are instead of si_end being a single value, it should be the last 11 digits and I need to make some sort of loop where the first time through, we find the largest digit in the left-most position (which I think find already does for us). And then that shrinks our candidates to be that position + 1.  It feels kind of recursive-y to me.  What do you think?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

Your intuition is spot on! This does have a recursive feel to it. The key insight is:

1. **For each digit position in your result**, you need to find the largest digit that still leaves enough digits remaining to complete the number.

For example, if you need 12 digits from a 15-character string:
- For the **first** digit, you can only look at positions 0, 1, 2, or 3 — because you need at least 11 more characters after your choice
- Once you pick position `p`, your next search starts at `p + 1`
- For the **second** digit, you again need to leave enough room for the remaining 10 digits
- And so on...

So the question at each step is: *"What's the largest digit I can pick while still leaving enough digits to finish?"*

You could do this recursively, or iteratively with a loop that tracks your current starting position and how many digits you still need. Either approach works well here.

Which way feels more natural to you — would you like to try the recursive approach, or would you prefer an iterative loop?

The escalator doesn't move. The Elf explains that it probably needs more joltage to overcome the static friction of the system and hits the big red "joltage limit safety override" button. You lose count of the number of times she needs to confirm "yes, I'm sure" and decorate the lobby a bit while you wait.

Now, you need to make the largest joltage by turning on exactly twelve batteries within each bank.

The joltage output for the bank is still the number formed by the digits of the batteries you've turned on; the only difference is that now there will be 12 digits in each bank's joltage output instead of two.

Consider again the example from before:

987654321111111
811111111111119
234234234234278
818181911112111
Now, the joltages are much larger:

In 987654321111111, the largest joltage can be found by turning on everything except some 1s at the end to produce 987654321111.
In the digit sequence 811111111111119, the largest joltage can be found by turning on everything except some 1s, producing 811111111119.
In 234234234234278, the largest joltage can be found by turning on everything except a 2 battery, a 3 battery, and another 2 battery near the start to produce 434234234278.
In 818181911112111, the joltage 888911112111 is produced by turning on everything except some 1s near the front.
The total output joltage is now much larger: 987654321111 + 811111111119 + 434234234278 + 888911112111 = 3121910778619.

I added the full instructions for part 2 above. Is there anything I'm misunderstanding or that is going to give me troubles?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

Looking at the problem and examples, your understanding looks solid! The greedy approach should work well here.

One small detail worth double-checking: when there are **ties** (multiple occurrences of the largest digit in your valid range), you want to pick the **leftmost** one. This gives you the most flexibility for the remaining digits.

For example, in `"234234234234278"`:
- You need 12 digits from 15, so for your first digit you can search positions 0–3
- Positions 0–3 are `2, 3, 4, 2` — the largest is `4` at position 2
- Now you search from position 3 onward for your second digit, and so on...

Your Part 1 code used `find()`, which naturally returns the leftmost occurrence — so that's good! Just make sure you preserve that behavior when you adapt it.

Does that all make sense? Ready to give the implementation a try?

Ok, so I need to create a function that takes in a string of digits, the current position, and the total number of digits is that correct?  

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

Yes, that's a solid foundation! Those parameters give you what you need to figure out:
- Where you can search (from `current_position` to some upper bound)
- How far you can go (based on how many digits you still need)

One thing to think about: what should the function **return**? And will you pass "total digits needed" or "digits remaining to find"? Either can work, but one might feel cleaner as you recurse.

What are you thinking for the return value?

I should probably pass the current digit through the recursive function and then my stop condition should be when we reach the end digit value.  Maybe we could start by recreating the 2 digit solution and then ramp it up to 12 once we get the 2 digit version working properly. How does that sound?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

That's an excellent plan! Starting with 2 digits to validate your logic before scaling up to 12 is a smart approach — much easier to debug.

So for your 2-digit version, you'd have:
- **Base case**: when you've found your 2nd (final) digit, return or accumulate the result
- **Recursive case**: find the best digit in your valid range, then recurse to find the next one

Go ahead and give it a try! You can test against your sample input where you already know the expected answers. Let me know if you get stuck or want to talk through any part of it.

Can you give me variable names to start?  Maybe just create the skeleton of my function for me and I will fill it in

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

Sure! Here's a skeleton to get you started:

```python
def find_largest(digits, start_pos, num_remaining):
    # Base case: when num_remaining == 1, what should you return?
    
    # Calculate the furthest position you can search
    # (hint: you need to leave room for the remaining digits)
    
    # Find the largest digit in your valid search range
    
    # Recurse to find the rest
    
    pass
```

You can call it with something like `find_largest(si, 0, 2)` to find the 2-digit answer for a line `si`.

Does that give you enough to work with?

In [ ]:
def find_largest(digits:str, num_remaining):
    if num_remaining == 1: 
        sorted_digits = sorted(digits, reverse=True)
        largest_digit = sorted_digits[0]
        return largest_digit
    else:
        sorted_digits = sorted(digits[:-num_remaining+1], reverse=True)
        largest_digit = sorted_digits[0] 
        largest_digit_position = digits.find(largest_digit)
        largest_digit+=find_largest(digits[largest_digit_position+1:], num_remaining-1)
    return largest_digit

In [ ]:
total_output_joltage=0
for si in sample_input.splitlines():
    total_output_joltage+=int(find_largest(si, 12))
total_output_joltage

3121910778619

In [ ]:
# Testing on Part 1 with new recursive method
total_output_joltage=0
for i in instructions: 
    total_output_joltage+=int(find_largest(i, 2))
total_output_joltage

17109

In [ ]:
total_output_joltage=0
for i in instructions: 
    total_output_joltage+=int(find_largest(i, 12))
total_output_joltage

169347417057382

That worked.  I keep thinking there is something better I should do with my recursive function with my sorted_digits and largest_digits.  It feels like I am almost repeating a lot of code between the if and else statement.  Any ideas for me to have less separated code between my base case?

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

Nice observation! You're right — both branches are doing similar work.

Here's a hint: notice that when `num_remaining == 1`, the valid search range is actually *all* of `digits`. And your slice `digits[:-num_remaining+1]` would give you `digits[:-0]` which is empty — so your base case is actually working around a quirk of Python slicing!

What if you used `digits[:len(digits) - num_remaining + 1]` instead? Try working out what that gives you when `num_remaining` is 1 versus when it's larger.

If that works uniformly, you might be able to have just one path that always finds the largest digit, and then decides whether to recurse based on `num_remaining`.

Want to give that a try?

My brain is a little fried, can you implement it?  I'm pretty sure I get what you are saying though!

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

Of course! Here you go:

```python
def find_largest(digits: str, num_remaining):
    search_end = len(digits) - num_remaining + 1
    sorted_digits = sorted(digits[:search_end], reverse=True)
    largest_digit = sorted_digits[0]
    largest_digit_position = digits.find(largest_digit)
    
    if num_remaining == 1:
        return largest_digit
    else:
        return largest_digit + find_largest(digits[largest_digit_position + 1:], num_remaining - 1)
```

The key change is using `len(digits) - num_remaining + 1` to calculate the search range, which works correctly for all cases including when `num_remaining == 1`. Now the only difference between the branches is whether you recurse or not!

In [ ]:
# I like this version slightly more than my original because there is less repeated code. :)
def find_largest(digits: str, num_remaining):
    search_end = len(digits) - num_remaining + 1
    sorted_digits = sorted(digits[:search_end], reverse=True)
    largest_digit = sorted_digits[0]

    if num_remaining == 1:
        return largest_digit
    else:
        largest_digit_position = digits.find(largest_digit)
        return largest_digit + find_largest(digits[largest_digit_position + 1:], num_remaining - 1)

In [ ]:
total_output_joltage=0
for i in instructions: 
    total_output_joltage+=int(find_largest(i, 12))
total_output_joltage

169347417057382